# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    # This parameter defines the codes of the locales (languages) enabled in the application
    #app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN
    jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem' # ssh private key path
    jwt_public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'  # ssh public key path
    jwt_key_pass_phrase:  'michal'                                         # ssh key pass phrase
    jwt_token_ttl:        3600

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        # defines the scalar arguments once and apply them to any service defined/created in this file
        #bind:
            #$locales: '%app_locales%'
            #$defaultLocale: '%locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Tests,Handler}'

    App\Handler\:
        resource: '../src/Handler'
        public: true

    App\Utils\CharacterCrawler:
        factory: 'App\Utils\CrawlerFactory:get'
        arguments:
            $crawler: 'character'

    App\Utils\GuildCrawler:
        factory: 'App\Utils\CrawlerFactory:get'
        arguments:
            $crawler: 'guild'

    App\Utils\UserCrawler:
        factory: 'App\Utils\CrawlerFactory:get'
        arguments:
            $crawler: 'user'

    App\Utils\UserCharacterCrawler:
        factory: 'App\Utils\CrawlerFactory:get'
        arguments:
            $crawler: 'user-character'
